### ISSUE TITLE
Error listing school

### ISSUE THREAD

**Issue by bitcoin4cashqc** [nnormandin/AutoTinder#2]
Traceback (most recent call last):
  File "tinderly.py", line 291, in <module>
    getNearUser()
  File "tinderly.py", line 108, in getNearUser
    users = session.nearby_users()
  File "/home/line/Bureau/1important/webdev/Tinderly/pynder/session.py", line 35, in nearby_users
    ret.append(Hopeful(u,self))
  File "/home/line/Bureau/1important/webdev/Tinderly/pynder/models/user.py", line 27, in __init__
    self.schools_id.extend([school["id"] for school in data['schools']])
  File "/home/line/Bureau/1important/webdev/Tinderly/pynder/models/user.py", line 27, in <listcomp>
    self.schools_id.extend([school["id"] for school in data['schools']])
KeyError: 'id'

I just removed pynder with pip3, and cloned AutoTinder

**Comment by bitcoin4cashqc** [comment]
Fixed myself like a grownup from original pynder

```
class User(object):

    def __init__(self, data, session):
        self._session = session
        self._data = data
        self.id = data['_id']

        for field in SIMPLE_FIELDS:
            setattr(self, field, data.get(field))

        self.photos_obj = [photo for photo in data['photos']]
        self.birth_date = dateutil.parser.parse(self.birth_date)
        self.schools = {}
        self.jobs = []
        try:
            self.schools.update({school["id"]: school["name"] for school in data['schools'] if 'id' in school and 'name' in school})
            self.jobs.extend(["%s @ %s" % (job["title"]["name"], job["company"]["name"]) for job in data['jobs'] if 'title' in job and 'company' in job])
            self.jobs.extend(["%s" % (job["company"]["name"],) for job in data['jobs'] if 'title' not in job and 'company' in job])
            self.jobs.extend(["%s" % (job["title"]["name"],) for job in data['jobs'] if 'title' in job and 'company' not in job])
        except (ValueError, KeyError):
            pass
```
